### ISSUE TITLE
currency rate conversion to allow working with non PKR default currency

### ISSUE THREAD

**Issue by Aceipro687** [FahadYousafMahar/Easypay-WHMCS-Gateway#10]
can you please Add WHMCS's own currency rate conversion to allow working with non PKR default currency.

**Comment by FahadYousafMahar** [comment]
If you need to use currency rate conversion please upgrade to PRO version of the gateway available at [Webit.pk's Easypaisa PRO Redirection Based Module](https://webit.pk/billing/cart.php?a=add&pid=136)
