### ISSUE TITLE
IPN handler. 

### ISSUE THREAD

**Issue by waqaspuri** [FahadYousafMahar/Easypay-WHMCS-Gateway#5]
**What IPN handler parameters should I use ?**

**Comment by FahadYousafMahar** [comment]
Can you describe what do you mean by parameters? 
If you mean the parameters sent back to call back from Easypay's IPN, then you should send back all parameters if you want.

**Comment by waqaspuri** [comment]
thanks fahad. it works, actually the Test/Mode function is disabled by
easypaisa. it has to be without testing mode. Fahad. that is the great
plugin you have set up for free. good work. what should be the call back ?
how do i know the call back is working fine?

**Comment by FahadYousafMahar** [comment]
There are some problems currently going on with callback... It was an issue on Easypaisa's side... I don't know if it has been resolved.. 

Still callback url will be the path to your website.com/path/to/callback/easypay.php file. 

Let me know if you receive an IPN response .

**Comment by waqaspuri** [comment]
Last question. I can see the payment page. will it work ok, In-case of call
back not working

**Comment by FahadYousafMahar** [comment]
When the callback is not working, the system will not register any payments automatically.
In that case, you'll need to manually verify the payment from your Easypaisa portal and then Accept the order accordingly from WHMCS admin area.

**Comment by waqaspuri** [comment]
thanks for the great and very comprehensive response. i appreciated you immediate response. so at this moment call back works but often it might causes some error. not all the time

**Comment by waqaspuri** [comment]
a customer attempt to charge the credit card to my WHMCS portal, it works through your script nicely, and the customer sees the invoice successful message. but the invoice did not automatically set to paid by WHMCS after the successful transaction, as you mentioned that that is the callback issue with the telenor easypaisa. Is it that issue @FahadYousafMahar. What are the ways to resolve it.

**Comment by FahadYousafMahar** [comment]
At current there are no ways to resolve it.  It is a problem at Easypaisa's end and though I have been in contact with them for months , they are not getting anywhere on this issue. 
You can also report it to Mr hamid Noor hamid.noor@telenorbank.pk who's from technical dept

**Comment by FahadYousafMahar** [comment]
There's one way to overcome this and that requires periodic lookups for transaction status using Transaction Token or ID.

I don't know if it's possible currently. I'll have to look whole transaction flow and check with Integration Guide to see if it's possible.

**Comment by waqaspuri** [comment]
I have also email to WHMCS support if they can suggest. I can see call back function is fine. and the callback addInvoicePayment is required to add the invoice information. that's it, may I know if **`addInvoicePayment`** is being compiled why it doesn't add the invoice details. ?

**Comment by FahadYousafMahar** [comment]
You are not getting what the real problem is. There's nothing to be done with any function in callback. 
Callback is just a file which needs to be opened with specific query parameter **URL**.
Easypaisa IPN sends that query parameter **URL** to callback file. The file then runs a curl command and gets transaction details and then adds the amount and transaction id to the invoice and invoice is marked paid automatically.

But now easypaisa IPN has some errors and it is not sending any IPN. Which means callback file receives no request with URL parameter. Hence the automation fails. 

You can write this code on first line of callback/easypay.php to log all requests to callback and see what's happening.
 
```<?php
file_put_contents('ep.log',print_r($_REQUEST, true)."\n\n",FILE_APPEND);
```
It'll create a ep.log file in your callback directory. 

You'll also find that preliminary token generation and status requests at the end of checkout at Easypaisa's hosted page are received. 
But no request contains URL parameter which is sent by IPN.

**Comment by waqaspuri** [comment]
You're right about the call back issue that is definitely from the easypaisa. as am sending the manual IPN + removing few if params to check the process but the it doesnt even seems reflecting to EasyPaisa.php call back. it is too helpful to disucss with matter with you. I will now check back with the telenor easypisa and will let you know if any suggestion by easypaisa technical team.

**Comment by waqaspuri** [comment]
```
Array
(
    [success] => true
    [batchNumber] => 20200765
    [amount] => 3600.0
    [orderRefNumber] => 1872
    [transactionResponse] => Transaction Successful.
)
```

it returns something like that after a successful transaction through CC by one of our customer. but still the invoice was unpaid

**Comment by FahadYousafMahar** [comment]
Any guy can send such a response and system can be fooled if I were looking up transaction with this response. 
Instead, IPN sends a url of a transaction which is looked up through curl and all the details received are then matched wih customer's transaction number and invoice number. So, the authenticity and uniqueness of transaction is verified and then the payment is added to invoice. 

That is why callback uses URL parameter sent by IPN :)

**Comment by waqaspuri** [comment]
Very logical reply. I have no words to respond back :-) stay blessed;
JazakAllah.
