### ISSUE TITLE
transaction attempt

### ISSUE THREAD

**Issue by waqaspuri** [FahadYousafMahar/Easypay-WHMCS-Gateway#6]
a customer attempt to charge the credit card to my easypaisa, it works through your script. and the invoice also shows a successful message. but I had a simple issue. the invoice was unpaid even after invoice shows a message transaction successful. going through everything in the program, it is better to take advice from you. please help as you've been always being helping me in this.

**Comment by srscoderz** [comment]
@waqaspuri I am facing the same issue as well!

**Comment by FahadYousafMahar** [comment]
You can use Easypay Pro Redirect Module from whmcs marketplace to fix the issue temporarily. It was caused by easypaisa IPN server's fault. A hackfix have been applied in new module to workaround it.
