### ISSUE TITLE
Transaction not added to whmcs invoice after successfull payment via CC

### ISSUE THREAD

**Issue by srscoderz** [FahadYousafMahar/Easypay-WHMCS-Gateway#9]
Good script! Marvelous work done by you and your team. 

I have successfully integrated this module to my WHMCS installation. There's a little problem I am facing with the transaction process. Following are the details.

1. I created a test invoice for Rs. 10/-
2. When paying through Credit card via Easypay, after verifying through OTP with my credit card provider, I proceeded next.
3. Payment was successful and I received a message and an email from Easypaisa. 
4. It took me back to IPN Handler URL: https://website/modules/gateways/callback/EasyPay.php
5. Invoice was displayed back with success message, but **there was no transaction added to it** so technically invoice is still unpaid. But **transaction is listed in Easypay Merchant Portal**.
6. I also **did not received transaction message or email from my credit card provider company**, but I checked the cc statement, transaction was settled there after 3 days.

Could you please help me whats wrong?

**Comment by FahadYousafMahar** [comment]
@srscoderz  It is an issue with EasyPaisa's IPN Handler. 
Easypaisa's system is not sending IPN back.
[See my previous replies](https://github.com/FahadYousafMahar/Easypay-WHMCS-Gateway/issues/5#issuecomment-662336829)
[View previous issue #5   
](https://github.com/FahadYousafMahar/Easypay-WHMCS-Gateway/issues/5)

A workaround has been made available at [Webit.pk's Easypaisa PRO Redirection Based Module](https://webit.pk/billing/cart.php?a=add&pid=136)
